version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: "mariadb:latest"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=kaddem
    networks:
      - my_network



  equipe_app:
    build: ./
    image: arijhajji-5TWIN4-G3-kaddem
    restart: unless-stopped
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/kaddem?autoReconnect=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    networks:
      - my_network




volumes:
  db_vol:

networks:
  my_network: