# Stage 1: Construire l'application Angular
FROM node:16.15 AS builder

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

# Réinitialiser les configurations de proxy npm
RUN npm config delete proxy
RUN npm config delete https-proxy

# Configurer le registre npm avec un miroir différent (si nécessaire)
RUN npm config set registry https://registry.npmjs.org/


# Installer les dépendances
RUN npm install

# Copier le reste du code de votre application
COPY . .

# Construire l'application Angular
RUN npm run build --prod

CMD ["npm", "start"]

# Stage 2: Créer l'image Nginx pour servir l'application construite
FROM nginx:alpine

# Copier la configuration Nginx
COPY src/ngnix/etc/conf.d/default.conf /etc/nginx/conf.d/default.conf

# Copier les artefacts de construction depuis l'étape de construction
COPY --from=builder /usr/src/app/dist/kaddem /usr/share/nginx/html
